import { z } from "zod";

const clientEnv = z.object({
  NEXT_PUBLIC_ORIGIN_URL: z.string().url(),
  NEXT_PUBLIC_API_URL: z.string().url(),
  NEXT_PUBLIC_ADS_URL: z.string().url(),
  NEXT_PUBLIC_NOADS_URL: z.string().url(),
  NEXT_PUBLIC_NODE_ENV: z.enum(["development", "production"]),
  NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_728x90: z.string(),
  NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_160x600: z.string(),
});

export default clientEnv.parse({
  NEXT_PUBLIC_ORIGIN_URL: process.env.NEXT_PUBLIC_ORIGIN_URL,
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_ADS_URL: process.env.NEXT_PUBLIC_ADS_URL,
  NEXT_PUBLIC_NOADS_URL: process.env.NEXT_PUBLIC_NOADS_URL,
  NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
  NEXT_PUBLIC_ADSTERRA_APIKEY_POPUNDER:
    process.env.NEXT_PUBLIC_ADSTERRA_APIKEY_POPUNDER,
  NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_728x90:
    process.env.NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_728x90,
  NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_160x600:
    process.env.NEXT_PUBLIC_ADSTERRA_APIKEY_BANNER_160x600,
});
